### ISSUE TITLE
Make it possible to detach X session from virtual tty.

### ISSUE THREAD

**Issue by crocket** [dopsi/console-tdm#17]
When I log in my desktop environment from console-tdm, tty1 is occupied by startx.
I can kill the X session on tty1 by pressing Ctrl+C. This feels fragile.

I don't know if what I want breaks the core tenet of console-tdm, but I'd like to hear others' thoughts.

**Comment by amakovec** [comment]
Hey @crocket!  Thanks for submitting this issue!

You're right that `/dev/tty1` (or the `tty` of your choosing) is occupied by `startx` while the `X` session is running, and if you were able to get to `stdin` of `/dev/tty1` then you would be able to send a kill signal (in your case, `^C`).  However, I can't seem to come up with a scenario where you're able to write to `/dev/tty1` while inside of an `X` session.  But if I could, that would feel fragile to me too.

If you may, could you tell me how you're able to send a kill signal to `startx`?  Also, if you could, what desktop environment are you using?  It would help quite a bit if you could provide a more detailed "steps to reproduce" for your issue.

Thanks!

**Comment by crocket** [comment]
I use xmonad launched from `~/.xsession`.

I can press Ctrl+Alt+F1 to visit tty1 and press Ctrl+C. When I see startx on tty1, I feel very tempted to press Ctrl+C.

**Comment by amakovec** [comment]
I totally agree with the "temptation" analogy...  I'm not going to "accidentally" run a `killall startx`, but if I'm staring at a `tty` with a running `X` session, I'm more tempted to jab `^C`.  Good find!

Here's what I'm wondering now:  As an i3 user (and this is probably dependent on my .xinitrc configuration as well), `console-tdm` launches `startx` from `/dev/tty1` and thus `X` runs inside of `/dev/tty1`.  Therefore, I cannot directly view the virtual terminal for `/dev/tty1` since the graphical interface for `X` is occupying it.  I could technically send a kill signal to `/dev/tty1`, but this doesn't have the "temptation" factor we discussed prior.

So, I'm wondering why `xmonad` / `startx` is running `startx` from `/dev/tty1` but the `X` session runs in a different virtual terminal, or if this is even the case at all.

Would you be able to tell me what virtual terminal `X` is running on?  I've tried to find if there's an elegant way to check what `tty` `X` is currently running on, but I could find no such thing.  The best way to do this is probably to cycle through `Ctrl+Alt+F1-F7` until you find the `X` session.

If what I'm thinking is correct, a possible fix to this would be to make sure that `Xorg` starts on the same virtual terminal that `console-tdm` and `startx` were run from, possibly by using the `vtXX` option in `Xorg`.

**Comment by crocket** [comment]
I log in console-tdm on `tty1`, and I find my X session on tty7.

**Comment by dopsi** [comment]
@crocket Thanks for submitting this issue. I have personally never used `startx` this way (and did not even know you could detach an X session). I will have to look that up but this may take some time. If you find a solution, you can submit a pull request.

**Comment by crocket** [comment]
I think you can test inserting the following snippet in `tdm`.

```
if [ -z $XDG_VTNR ]; then
  export XDG_VTNR=$(tty | sed -n -e 's|^/dev/tty\([1-9][0-9]*\)|\1|p')
fi
```

`/etc/X11/init/xserverrc` will check the presence of `$XDG_VTNR` and use it.
