### ISSUE TITLE
errors when starting into ncurse UI

### ISSUE THREAD

**Issue by theova** [dopsi/console-tdm#19]
Hello

When I'm starting into ncurses UI, I get the following errors:
```
/usr/bin/tdm: Line 199: [[:
Error: Unknown option .
Use --help to list options.: Syntaxfehler im Ausdruck. (Fehlerverursachendes Zeichen ist "\: Unknown option.
Use --help to list options."\).
/usr/bin/tdm: Line 201: [[:
Use --help to list options.: Syntaxfehler im Ausdruck. (Fehlerverursachendes Zeichen ist "\: Unknown option.
Use --help to list options."\).
Unknown value, load default
Session not defined, falback.
```
Running console-tdm into text UI, it works well. What can I do to get it running? If you need more informations, just tell me.

Thank you very much for your work!

**Comment by amakovec** [comment]
Hi @theova!  Thanks for reporting the issue!

**Short answer:** I've just submitted a pull request that fixes the issue.  You can view the pull request here: #20.

**Long answer:** I'll break down the debugging process here for anyone interested.  First, I went to the first line of code listed in your error log ([L199](https://github.com/dopsi/console-tdm/blob/334ce245064868128a6413c8a8ead30c06428767/tdm#L199)).  The syntax seemed fine, so I added an echo statement for each variable in the conditional and ran tdm.  `$sid` was set to a funky value, "`Unknown option .`", when it is supposed to be an integer.  As intended, `$sid` takes the stderr output of dialog, which when dialog completes successfully will return the integer of the Xorg session selected by the user.  However, dialog was not executing properly and returning the error seen above, "`Unknown option .`".  I then tried removing all variables from the arguments passed to dialog, replacing them with constants.  This resolved the bug.  I then, one-by-one, placed the variables back in, discovering that `"$DEFOPT"` is what broke the command.  As you can see in #20, `$DEFOPT` always contains `--default-item 0`, where 0 is the default item set by the user.  Since this variable was quoted in the arguments of dialog, `--default-item` and `0` were not split properly when the string was fed into dialog, and it was interpreted as one big flag instead of a "flag-value" pair.  Simply removing the quotes resolved the bug.

**Comment by dopsi** [comment]
Hi @theova,

Thanks for the issue report. It looks like @amakovec's PR fixes the bugs you're experiencing. I'll merge it as soon as it is ready.

**Comment by dopsi** [comment]
@theova I don't know how you run the program, but could you confirm that c55cbf6 fixes your issue ?

**Comment by theova** [comment]
Hello,

thank you, the problem is fixed, I'm now able to run the program :-)

I'm running it according to https://wiki.archlinux.org/index.php/Console_TDM with `~/.zprofile`.
