### ISSUE TITLE
logout when exiting session

### ISSUE THREAD

**Issue by aRmanNM** [dopsi/console-tdm#25]
use this to switch between my openbox and bspwm sessions. exiting each session i expect to logout but it goes back to bash or zsh prompt. then i should enter exit to actually logout. wonder if there is a way to implement such behavior without typing exit every time. tnx.

**Comment by dopsi** [comment]
The current workaround is to add `exit` in your bash profile right after the `source /usr/bin/tdm` line. I don't have time to work on that anytime soon, but I would accept pull requests.

This will however never be the default behavior, since this program is merely a wrapper around `startx`, which does not exit once the WM/DE closes.
