### ISSUE TITLE
console-tdm and i3

### ISSUE THREAD

**Issue by joex92** [dopsi/console-tdm#33]
Hi,
I'm kinda new to the "init" processes on Linux...
I have an Ubuntu-Server that occasionally use a screen to check it up, for that I use i3wm...
Everything works fine in the server, I just want to have this login screen and I don't understand how to use it... there are these "X" and "extra" modes you explain, but I don't how to call them or how to make them work at boot... 
Sorry if this is too "basic"...

I managed to install console-tdm, now what?

**Comment by dopsi** [comment]
# Different types of sessions

The two types of sessions determine if console-tdm attempts to start the X server or not:

- an `X` session will run `startx` and then run the actual session from inside the `.xinitrc` script
- an `extra` session will run the session directly, without starting an X server (this is useful for Wayland compositors among other things)

Since i3 is X-based, you want an X session.

# Startup process

The start process goes as follows:

1. either you or your `.bash_profile` script call the `tdm` executable (**without the `--xstart` argument**)
1. `tdm` queries you for which session you want to start
1. once the session is chosen, there are two cases:
  * it is an X session: `startx` is called, and the commands in your `.xinitrc` file are run. **`tdm` must be the last**. It will start the session you chose.
  * it is an `extra` session, the session is run directly in place

## Specific setup for i3

You want to add a session with 

```bash
tdmctl add i3 /usr/bin/i3
```

the edit the `.xinitrc` file and add the following line as last line:

```
exec tdm --xstart
```

If you want console-tdm to start when you log in on the TTY, you need to add the line

```
exec /usr/bin/tdm
```

to your `.profile` file

**Comment by FrostKnight** [comment]
Dopsi, thank you for maintaining this repository! I can use this probably anywhere BSD or Linux due to the minimal dependencies.  I owe you a lot of thanks!  :)
